version: '3'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./react
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:                                                                        
     - 80:8080
                                                                                            
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react/build
    depends_on:
      - backend
      - frontend
volumes:
  react_build:

